In [13]:
import pandas as pd

In [14]:
def split_text(text):
    return text.split()

In [17]:
train = pd.read_pickle('train.pkl')

In [19]:
train['temp_list'] = train['prompt'].apply(split_text)

In [20]:
train

,id,model_a,model_b,prompt,response_a,response_b,winner_model_a,winner_model_b,winner_tie,temp_list
0,30192,gpt-4-1106-preview,gpt-4-0613,morally right try certain percentage females m...,question whether morally right aim certain per...,ai dont personal beliefs opinions however tell...,1,0,0,"[morally, right, try, certain, percentage, fem..."
1,53567,koala-13b,gpt-4-0613,difference marriage license marriage certifica...,marriage license legal document allows couple ...,marriage license marriage certificate two diff...,0,1,0,"[difference, marriage, license, marriage, cert..."
2,65089,gpt-3.5-turbo-0613,mistral-medium,explain function calling would call function,function calling process invoking executing fu...,function calling process invoking function pro...,0,0,1,"[explain, function, calling, would, call, func..."
3,96401,llama-2-13b-chat,mistral-7b-instruct,create test set rare category want build class...,creating test set rare category challenging ma...,building classifier rare category creating tes...,1,0,0,"[create, test, set, rare, category, want, buil..."
4,198779,koala-13b,gpt-3.5-turbo-0314,best way travel telaviv jerusalem car bus plane,best way travel tel aviv jerusalem depends per...,best way travel telaviv jerusalem depends pers...,0,1,0,"[best, way, travel, telaviv, jerusalem, car, b..."
...,...,...,...,...,...,...,...,...,...,...
57472,4294656694,gpt-4-0613,claude-1,simple mnemonic uc wish could enumerate pi eas...,sure lets break letters letter wish letters le...,mnemonic represents digits uc letters uc lette...,1,0,0,"[simple, mnemonic, uc, wish, could, enumerate,..."
57473,4294692063,claude-2.0,llama-2-13b-chat,python implement naive bayes gaussian mixture ...,implementation naive bayes classifier gaussian...,sure heres implementation naive bayes classifi...,1,0,0,"[python, implement, naive, bayes, gaussian, mi..."
57474,4294710549,claude-1,alpaca-13b,unethical work building weaponsare deterrents ...,working weapons technology raises ethical ques...,depends context weapons used defensive purpose...,1,0,0,"[unethical, work, building, weaponsare, deterr..."
57475,4294899228,palm-2,tulu-2-dpo-70b,bait contains bromadiolon much adult rat needs...,bromadiolone rodenticide often used bait secon...,ai language model promote condone use poison h...,0,1,0,"[bait, contains, bromadiolon, much, adult, rat..."
57476,4294947231,gemini-pro-dev-api,gpt-4-1106-preview,three kids eat three apples three days many ap...,apples,three kids eat three apples three days kid eat...,1,0,0,"[three, kids, eat, three, apples, three, days,..."

In [21]:
train = {
    'temp_list': [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
}
from collections import Count
fl = Count([item for sublist in train['temp_list'] for item in sublist])
fl

ImportError: cannot import name 'Count' from 'collections' (C:\Users\Pakistan\AppData\Roaming\jupyterlab-desktop\jlab_server\Lib\collections\__init__.py)

In [23]:
import collections
dir(collections)

['ChainMap',
 'Counter',
 'OrderedDict',
 'UserDict',
 'UserList',
 'UserString',
 '_Link',
 '_OrderedDictItemsView',
 '_OrderedDictKeysView',
 '_OrderedDictValuesView',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_chain',
 '_collections_abc',
 '_count_elements',
 '_deque_iterator',
 '_eq',
 '_iskeyword',
 '_itemgetter',
 '_proxy',
 '_recursive_repr',
 '_repeat',
 '_starmap',
 '_sys',
 '_tuplegetter',
 'abc',
 'defaultdict',
 'deque',
 'namedtuple']